### PR TITLE
Prevent the user from making empty comments anbd blog posts

### PR DESCRIPTION
**Pull request by algo-1**
## Context
The user is allowed to make empty comments and blog posts

## Describe your changes
Added a condition for making or updating a comment to ensure input is not empty
Added conditions to make sure the blog title and content were not empty 
UI updates as well preventing the user from making clicking the buttons

## Issue ticket number and link
[CON-122](https://continuus.atlassian.net/browse/CON-122)

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [ ] If it is a core feature, I have added thorough tests.
- [x] I verified that my code will compile by running `npm run build` 
- [x] I have run `npm run lint` and fixed linting errors

### CODE REVIEW

**Review by scott-m-king — CHANGES_REQUESTED** [review]
can we maybe grey out and disable the button if the comment is just an empty string? maybe we can do this for the normal Post button as well

**Comment by algo-1** [comment]
> can we maybe grey out and disable the button if the comment is just an empty string? maybe we can do this for the normal Post button as well

Done

**Comment by scott-m-king** [comment]
If the tests are failing, you can run `npm run test -- -u` to update the snapshots, and then commit the snapshot changes

**Review by scott-m-king — APPROVED** [review]
thanks!!

**Pull request merged**
